import { strict as assert } from "node:assert";
import { parseGcode } from "../src/lib/gcode-parser";

const prusa = parseGcode("; generated by PrusaSlicer 2.8\n; filament used [g] = 42.35\n; estimated printing time (normal mode) = 1h 12m 30s\n; layer_height = 0.2");
assert.equal(prusa.slicer, "PrusaSlicer");
assert.equal(prusa.materialGrams, 42.35);
assert.equal(prusa.printSeconds, 4350);
assert.equal(prusa.layerHeight, 0.2);

const cura = parseGcode(";Generated with Cura_SteamEngine\n;TIME:3600\n;Filament weight = 18.5g\n;Filament used: 6.12m");
assert.equal(cura.slicer, "Cura");
assert.equal(cura.materialGrams, 18.5);
assert.equal(cura.printHours, 1);
assert.equal(cura.filamentMeters, 6.12);

const bambu = parseGcode("; generated by BambuStudio\n; total filament used [g] : 20.25\n; total estimated time: 5400s");
assert.equal(bambu.slicer, "Bambu Studio");
assert.equal(bambu.materialGrams, 20.25);
assert.equal(bambu.printHours, 1.5);

console.log("G-code parser passed: 11 checks");
